# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:02 uid42307 Exp $

TESTS += modules/objfmts/elf/tests/amd64/elf_amd64_test.sh

EXTRA_DIST += modules/objfmts/elf/tests/amd64/elf_amd64_test.sh
EXTRA_DIST += modules/objfmts/elf/tests/amd64/elf-rip.asm
EXTRA_DIST += modules/objfmts/elf/tests/amd64/elf-rip.hex
EXTRA_DIST += modules/objfmts/elf/tests/amd64/elfso64.asm
EXTRA_DIST += modules/objfmts/elf/tests/amd64/elfso64.hex
