# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:01 uid42307 Exp $

TESTS += modules/arch/lc3b/tests/lc3b_test.sh

EXTRA_DIST += modules/arch/lc3b/tests/lc3b_test.sh
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-basic.asm
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-basic.errwarn
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-basic.hex
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-br.asm
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-br.hex
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-ea-err.asm
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-ea-err.errwarn
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-mp22NC.asm
EXTRA_DIST += modules/arch/lc3b/tests/lc3b-mp22NC.hex
