# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:01 uid42307 Exp $

libyasm_a_SOURCES += modules/listfmts/nasm/nasm-listfmt.c

YASM_MODULES += listfmt_nasm

#EXTRA_DIST += modules/listfmts/nasm/tests/Makefile.inc

#include modules/listfmts/nasm/tests/Makefile.inc
