# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:01 uid42307 Exp $

EXTRA_DIST += modules/dbgfmts/stabs/tests/stabs_test.sh
TESTS += modules/dbgfmts/stabs/tests/stabs_test.sh

EXTRA_DIST += modules/dbgfmts/stabs/tests/stabs-elf.asm
EXTRA_DIST += modules/dbgfmts/stabs/tests/stabs-elf.hex
