
CC = gcc
INCDIR = -I../include/ -I../include/opt/ -I../host.support/ -I../lib/

ifndef UPTCPIP_INSTDIR
UPTCPIP_INSTDIR = ${PARSECDIR}/pkgs/libs/uptcpip/inst/${PARSECPLAT}
endif

ARCH = $(shell uname -i)

ifeq ($(ARCH), x86_64)
CFLAGS = -DX86_64 -D__LP64__
else
CFLAGS =  
endif


OS = $(shell uname -s)
ifeq ($(OS), Linux)
OS = $(shell uname -r)
TMP1 = $(subst -, , $(OS))
TMP2 = $(subst ., , $(TMP1))
OS = $(word 3, $(TMP2))

ifeq ($(OSVER), 9)
CFLAGS += -DOLD_LINUX
endif

#CFLAGS += -DOLD_LINUX
endif


GCC_OX = -O2  -g

# Run on real machines: 
#     using shared memory
CFLAGS += -rdynamic  -ffreestanding $(GCC_OX) -Wall -D_FREEBSD_KERNEL -D_GNU_SOURCE -DSMP  $(INCDIR)

# Run on Simulation: 
#     using socket
#CFLAGS += -rdynamic  -ffreestanding $(GCC_OX) -Wall -D_FREEBSD_KERNEL -D_GNU_SOURCE -DSMP -DFOR_SIMULATION $(INCDIR)


