# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:02 uid42307 Exp $

TESTS += modules/objfmts/elf/tests/gas32/elf_gas32_test.sh

EXTRA_DIST += modules/objfmts/elf/tests/gas32/elf_gas32_test.sh
EXTRA_DIST += modules/objfmts/elf/tests/gas32/elf_gas32_ssym.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas32/elf_gas32_ssym.hex
