# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:02 uid42307 Exp $

TESTS += modules/objfmts/xdf/tests/xdf_test.sh

EXTRA_DIST += modules/objfmts/xdf/tests/xdf_test.sh
EXTRA_DIST += modules/objfmts/xdf/tests/xdf-overdef.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdf-overdef.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdflong.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdflong.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdflong.errwarn
EXTRA_DIST += modules/objfmts/xdf/tests/xdfother.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdfother.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdfprotect.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdfprotect.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdfsect.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdfsect.hex
EXTRA_DIST += modules/objfmts/xdf/tests/xdfsect-err.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdfsect-err.errwarn
EXTRA_DIST += modules/objfmts/xdf/tests/xdfvirtual.asm
EXTRA_DIST += modules/objfmts/xdf/tests/xdfvirtual.hex
