include ../Makefile.config

OBJS = if_ether.o\
	igmp.o\
	in.o\
	in_gif.o\
	ip_id.o\
	in_mcast.o\
	in_pcb.o\
	in_proto.o\
	in_rmx.o\
	ip_ecn.o\
	ip_encap.o\
	ip_fastfwd.o\
	ip_icmp.o\
	ip_input.o\
	ip_options.o\
	ip_output.o\
	raw_ip.o\
	tcp_hostcache.o\
	tcp_input.o\
	tcp_lro.o\
	tcp_output.o\
	tcp_offload.o\
	tcp_reass.o\
	tcp_sack.o\
	tcp_subr.o\
	tcp_syncache.o\
	tcp_timer.o\
	tcp_timewait.o\
	tcp_usrreq.o\
	udp_usrreq.o\
    arc4random.o\
	 divdi3.o\
	 udivdi3.o\
	 harvest.o\
	 if.o\
	 if_gif.o\
	 if_loop.o\
	 if_llatbl.o\
	 in_cksum.o\
     inet_ntoa.o\
	 md5c.o\
	 netisr.o\
	 radix.o\
	 route.o\
	 uipc_domain.o\
	 uipc_mbuf2.o\
	 uipc_mbuf.o\
	 uipc_sockbuf.o\
	 uipc_socket.o\
	 strlcpy.o\
	qdivrem.o\
	subr_sbuf.o\
	kern_subr.o\
	support.o

all: $(OBJS)

clean:
	rm *.o -rf

#	 strcat.o
#	 strlen.o
#	 strcmp.o

#	 strncmp.o
#	 strcpy.o

