# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:02 uid42307 Exp $

TESTS += modules/objfmts/coff/tests/coff_test.sh

EXTRA_DIST += modules/objfmts/coff/tests/coff_test.sh
EXTRA_DIST += modules/objfmts/coff/tests/cofftest.c
EXTRA_DIST += modules/objfmts/coff/tests/cofftest.asm
EXTRA_DIST += modules/objfmts/coff/tests/cofftest.hex
EXTRA_DIST += modules/objfmts/coff/tests/cofftimes.asm
EXTRA_DIST += modules/objfmts/coff/tests/cofftimes.hex
EXTRA_DIST += modules/objfmts/coff/tests/x86id.asm
EXTRA_DIST += modules/objfmts/coff/tests/x86id.hex
EXTRA_DIST += modules/objfmts/coff/tests/x86id.errwarn
