# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:03 uid42307 Exp $

TESTS += modules/objfmts/macho/tests/nasm32/macho32_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.c
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/machotest.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-reloc.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho-reloc.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32-sect.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32-sect.errwarn
EXTRA_DIST += modules/objfmts/macho/tests/nasm32/macho32-sect.hex
