# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:00 uid42307 Exp $

TESTS += modules/parsers/nasm/tests/worphan/nasm_worphan_test.sh

EXTRA_DIST += modules/parsers/nasm/tests/worphan/nasm_worphan_test.sh
EXTRA_DIST += modules/parsers/nasm/tests/worphan/orphanwarn.asm
EXTRA_DIST += modules/parsers/nasm/tests/worphan/orphanwarn.errwarn
EXTRA_DIST += modules/parsers/nasm/tests/worphan/orphanwarn.hex
