# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:02 uid42307 Exp $

TESTS += modules/objfmts/elf/tests/gas64/elf_gas64_test.sh

EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_test.sh
EXTRA_DIST += modules/objfmts/elf/tests/gas64/crosssect.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas64/crosssect.hex
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_curpos.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_curpos.hex
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_reloc.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_reloc.hex
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_ssym.asm
EXTRA_DIST += modules/objfmts/elf/tests/gas64/elf_gas64_ssym.hex
