# Makefile for the PARSEC hooks library
#
# Copyright (C) 2006-2009 by Princeton University
# Author: Christian Bienia

PREFIX=${PARSECDIR}/pkgs/libs/parmacs/inst/${PARSECPLAT}

all: 
	@echo "NOP" > /dev/null

clean:
	@echo "NOP" > /dev/null

install:
	mkdir -p $(PREFIX)
	cp -rf * $(PREFIX)
	@rm $(PREFIX)/Makefile

.PHONY: all clean install

