# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:03 uid42307 Exp $

TESTS += modules/objfmts/macho/tests/gas64/gas_macho64_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas_macho64_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64.asm
EXTRA_DIST += modules/objfmts/macho/tests/gas64/gas-macho64.hex
