# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:03 uid42307 Exp $

TESTS += modules/objfmts/macho/tests/gas32/gas_macho32_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/gas32/gas_macho32_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/gas32/gas-macho32.asm
EXTRA_DIST += modules/objfmts/macho/tests/gas32/gas-macho32.hex
