# $Id: Makefile.inc,v 1.1.1.1 2012/03/29 17:21:03 uid42307 Exp $

TESTS += modules/objfmts/macho/tests/nasm64/macho64_test.sh

EXTRA_DIST += modules/objfmts/macho/tests/nasm64/macho64_test.sh
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.c
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/machotest64.hex
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/macho-reloc64-err.asm
EXTRA_DIST += modules/objfmts/macho/tests/nasm64/macho-reloc64-err.errwarn
